title: "Phủi Bụi Lãng Quên"
description: "Blog truyện và tác phẩm chọn lọc"
baseurl: "/my-reading-blog"
url: "https://PhamQuyMui43.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - templates
  - mau