title: "Phủi Bụi Lãng Quên"
description: "Blog truyện và tác phẩm chọn lọc"
baseurl: "/my-reading-blog"
url: "https://ten-user-cua-ban.github.io"
exclude:
  - README.md
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - templates
  - mau